# Generated by Django 5.1.6 on 2025-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prifile_picture',
            new_name='profile_picture',
        ),
    ]
