# Generated by Django 5.1.6 on 2025-03-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_prifile_picture_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='State',
            new_name='state',
        ),
    ]
