# Generated by Django 5.1.6 on 2025-03-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='userprofile',
            new_name='user_profile',
        ),
    ]
