# Generated by Django 5.1.6 on 2025-03-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_userprofile_vendor_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_name',
            new_name='name',
        ),
    ]
