# Generated by Django 5.1.6 on 2025-03-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_prifile_picture_userprofile_profile_picture'),
        ('vendors', '0003_rename_vendor_name_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.userprofile'),
        ),
    ]
